### ISSUE TITLE
Add Support for Nullables

### ISSUE THREAD

**Issue by OmarElabd** [OmarElabd/ObjectExporter#21]

**Comment by OmarElabd** [comment]
implemented

**Comment by pawciut** [comment]
In version 1.2.4 nullable Guids are incorrect. They are present at C# code as 
"new System.Guid?{	}" without property name to be assigned to.


example:

TypeCode = null,
new System.Guid?
{
},
TypeName = null,
Version = null,

**Comment by pawciut** [comment]
or something like this:

Description = "Status główny",
DocumentId
Id
new System.Guid?
	{
	},
new System.Guid?
        {
	},

**Comment by OmarElabd** [comment]
Thanks @pawciut for bringing this to my attention. You are right, they are not being handled correctly. I've created a new issue #43 to address this.
