### ISSUE TITLE
DateTime with month twice

### ISSUE THREAD

**Issue by robertbrooker** [OmarElabd/ObjectExporter#26]
I've seen output with the month twice for DateTimes.

I think this line of code might be questionable:

https://github.com/OmarElabd/ObjectExporter/search?utf8=%E2%9C%93&q=%22dateTime.Month%2C+dateTime.Month%22

**Comment by OmarElabd** [comment]
It does look fishy indeed, i'll give it proper look tomorrow and apply the fix. Really appreciate you bringing it to my attention.

**Comment by OmarElabd** [comment]
Fixed, will be released with version 2.0 in December
