### ISSUE TITLE
Base class properties

### ISSUE THREAD

**Issue by StonePit** [OmarElabd/ObjectExporter#45]
Please add (option) for base class properies

**Comment by OmarElabd** [comment]
Currently it sets the base class properties of an object, did you want an option to ignore setting that?

**Comment by StonePit** [comment]
Hi Omar, I found that it was not working in VS2012 but in 2015 works, it's sets the base class properties.
Another thing I found, some of propeties are not generated correctly (only initializer) see att. property Warehouse or RequestedDateTime (compare this two pics). Your tool realy saves a lot of time, thanks in advance Omar.
![obj1](https://cloud.githubusercontent.com/assets/16380405/11950327/ad73b4ea-a887-11e5-8906-b56d496e79c4.PNG)
![obj2](https://cloud.githubusercontent.com/assets/16380405/11950326/ad7337e0-a887-11e5-8d25-57012774b8f3.PNG)

**Comment by OmarElabd** [comment]
That's interesting, i'll look into why it's having issues in 2012. As for RequestDateTime, that's currently an issue with Nullables that has been fixed but hasn't been release yet, look for a major release after the Holiday break that should address both those issues. 

I'll close this issue and open a new one regarding inconsistent visual studio versions, there's already one regarding nullables.

I appreciate you taking the time to open an issue and I'm glad you find the tool useful.
