### ISSUE TITLE
Unable to start Object Explorer in Visual Studio

### ISSUE THREAD

**Issue by vurso** [OmarElabd/ObjectExporter#59]
Hi when starting visual studio an error is displayed stating the add-in could not be loaded.  I found the following information when I checked the activity monitor log:

17:51:13.373 
222 ERROR LegacySitePackage failed for package [ObjectExporter]Source: 'ObjectExporter' Description: Could not find SciLexer.dll - This is unmanaged assembly is required by ScintillaNet.dll System.DllNotFoundException: Could not find SciLexer.dll - This is unmanaged assembly is required by ScintillaNet.dll at ObjectExporter.VsPackage.ObjectExporter.LoadUnmanagedLibraries() at ObjectExporter.VsPackage.ObjectExporter.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) {07FB5B16-F4BE-4488-9A19-B4F36D2C05A6} 80131524 VisualStudio 2016/11/05 17:51:14.327 
223 ERROR SetSite failed for package [ObjectExporter](null) {07FB5B16-F4BE-4488-9A19-B4F36D2C05A6} 80131524 VisualStudio 2016/11/05 17:51:14.343

**Comment by vurso** [comment]
625 ERROR LegacySitePackage failed for package [ObjectExporter]Source: 'ObjectExporter' Description: Could not find SciLexer.dll - This is unmanaged assembly is required by ScintillaNet.dll System.DllNotFoundException: Could not find SciLexer.dll - This is unmanaged assembly is required by ScintillaNet.dll at ObjectExporter.VsPackage.ObjectExporter.LoadUnmanagedLibraries() at ObjectExporter.VsPackage.ObjectExporter.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) {07FB5B16-F4BE-4488-9A19-B4F36D2C05A6} 80131524 VisualStudio 2016/11/05 18:08:41.220 
626 ERROR SetSite failed for package [ObjectExporter](null) {07FB5B16-F4BE-4488-9A19-B4F36D2C05A6} 80131524 VisualStudio 2016/11/05 18:08:41.251 
627 ERROR End package load [ObjectExporter]

**Comment by OmarElabd** [comment]
Hi @vurso ,

SciLexer.dll is used by ObjectExporter, it should have been installed when you installed the .vsix project. May i ask what version of Visual Studio are you using?

I quick fix is putting [SciLexer.dll](https://github.com/OmarElabd/ObjectExporter/blob/master/ObjectExporter.VsPackage/SciLexer.dll) in the extension path C:\Users\<UserName>\AppData\Local\Microsoft\VisualStudio\<version>\Extensions\<object exporter hash>\

**Comment by vurso** [comment]
Hi @OmarElabd I checked the installation location all the files seemed to be there and I also tried to copy over the SciLexer.dll still no luck.

The first environment is a Windows 2008 R2 server with Visual Studio 2015 Community Edition with the latest updates.

The second environment is a Windows 10 Pro laptop with Visual Studio 2015 Community Edition.

Both environments experience the same issue

![image](https://cloud.githubusercontent.com/assets/997532/20200551/b9c86b38-a7a9-11e6-96a2-098bb99a00e5.png)

![image](https://cloud.githubusercontent.com/assets/997532/20200601/f719385a-a7a9-11e6-939e-674256280b04.png)

**Comment by chking999** [comment]
I'm getting this same error after I install Object Exporter to VS 2015.

**Comment by OmarElabd** [comment]
@chking999 What edition of VS 2015 are you using? Community as well?

**Comment by chking999** [comment]
Using Visual Studio Professional 2015
Version 14.0.25431.01 Update 3

Christian King
www.chking.com

**Comment by seba-0** [comment]
Same thing here. VS 2015 Enterprise Update 3, Win 10 x64 Enterprise. I debugged this and reason for this message, at least in my case, is because call to LoadLibrary fails with error 0x0000045A ERROR_DLL_INIT_FAILED. Scintilla dll exists and extension is correctly determining path to it.

**Comment by vurso** [comment]
This is still an issue.  Brand new laptop (Windows 10 Professional X64), McAfee AV installed, Visual Studio 2015 Professional with ReSharper (latest version), no other add-ins same error when Visual Studio starts up.

**Comment by OmarElabd** [comment]
@vurso do you have any other language packs installed except English? Either in Visual Studio or on Windows?

**Comment by vurso** [comment]
@OmarElabd hi nope its a clean Windows 10 Professional environment on my work laptop.  I used the MSDN subscription given to me by my manager to download Visual Studio 2015 Professional Edition.  I then installed the latest version of ReSharper and ApexSQL.

It is still showing that error message regardless of whatever I try (I do start VS in Administrator mode).

**Comment by OmarElabd** [comment]
External dlls are no longer loaded by object exporter, so this should no longer be an issue.

**Comment by seba-0** [comment]
Just to mention with release 1.7.0 issue is resolved for me. Thanks.

**Comment by OmarElabd** [comment]
@seba-0 excellent, glad to hear it.

**Comment by vurso** [comment]
Latest version works great good work bro!
