### ISSUE TITLE
Cannot see menu item in Tools

### ISSUE THREAD

**Issue by ac-erlang** [OmarElabd/ObjectExporter#67]
Looks like a great tool for unit testing.

I installed on my main machine running VS 2015 pro (Administrator)

Also I tried on my laptop, running community edition.

Neither show the menu item.  Please help?

Thanks

**Comment by OmarElabd** [comment]
@ac-erlang Are you debugging your code and stopped at a breakpoint?

**Comment by ac-erlang** [comment]
Ah ok - thanks!
